### ISSUE TITLE
Add maintainers

### ISSUE THREAD

**Issue by sandstrom** [ipaddress-gem/ipaddress#118]
Have you considered adding more maintainers? 

For example this guy @Adam21e has already created a fork at put in some work. If you'd add him I'm sure he can help merge some PRs and close down old issues.

I'm also willing to help, but think it would be better with someone that has already contributed PRs or worked on the code base.

**Comment by sandstrom** [comment]
friendly ping @francisluong

**Comment by bluemonk** [comment]
Yes good idea. Added! 
Thank you @sandstrom

**Comment by Adam21e** [comment]
thanks for the invite but it seems to have expired.
