### ISSUE TITLE
different result between IPAddress and IPAddr when call to_i

### ISSUE THREAD

**Issue by malongshuai** [ipaddress-gem/ipaddress#121]
```
>> require 'ipaddr'
>> require 'ipaddress'
>> IPAddr.new("172.16.10.1/24").to_i
=> 2886732288
>> IPAddress("172.16.10.1/24").to_i
=> 2886732289
```

**Comment by Adam21e** [comment]
Looks like the subnet affects IPAddr and it returns the network IP 172.16.10.0 and not the IP address.
```
>> IPAddr.new("172.16.10.1").to_i
=> 2886732289
```
I would consider 2886732289 to be the expected result as the subnet shouldn't matter when converting an IP address to an integer.
