### ISSUE TITLE
Is this library dead?

### ISSUE THREAD

**Issue by jcoetzee** [ipaddress-gem/ipaddress#126]
Based on the state of issues/PRs/releases it seems like this project has been abandoned; which would be disappointing but I understand that life and priorities change. Would be great however if the README/documentation was updated to indicate this - or better - if it was handed over to someone/community to take over (maybe @Adam21e would volunteer and merge back in from their fork?). Personally, I invested time implementing a project using this library (due to handy `summarize` method) only to find later that it, as well as other functionality like `last` and `subnet`, are not defined for IPv6 addresses.

**Comment by bluemonk** [comment]
Hello Jonathan,

The library is not dead, although it's true I have much less time to dedicate to it. 

There are members and collaborators attached to the project. Some have gone inactive, but we're still welcoming anyone to join the team. Please let me know if you would be interested!

**Comment by sandstrom** [comment]
@bluemonk I think this library is great, and it's very mature. I'd say more or less "complete".

How about releasing a 1.0 version? To signal that this is a mature library (it's already very widely used).

**Comment by ndbroadbent** [comment]
This was driving me crazy, I couldn't figure out why I was getting this error:

```
NoMethodError: undefined method `link_local?' for #<IPAddress::IPv4:0x00007faef0051dc8>
```

I didn't realize the version on Rubygems is so old. A new release would be greatly appreciated. For now I'll point directly to the GitHub repo

**Comment by bluemonk** [comment]
> @bluemonk I think this library is great, and it's very mature. I'd say more or less "complete".
> 
> How about releasing a 1.0 version? To signal that this is a mature library (it's already very widely used).

I don't know if it's very mature (some methods are still broken) but I think releasing 1.0 is indeed a great idea. Might work on it in the next few weeks, if anyone is interested in helping, you're welcome!

**Comment by sandstrom** [comment]
@bluemonk One suggestion would be to open up the discussions tab for this repo (under settings), then move every issue that is more of a feedback or wish into that tab. There is a dedicated button you can click on each issue, "Move to discussion" or something along those lines.

That way, you can easily cleanup the issue list a bit. Happy to help if you give me access.

Then perhaps open a small meta issue with stuff that you'd like to do before 1.0. Try to keep this list as short as possible, most things are better left for 1.1 or 1.2.

I can have a look at that list and see if there is something I can help out with.

**Comment by bluemonk** [comment]
@sandstrom Great, let's do that!

**Comment by sandstrom** [comment]
Closing this issue. Tracking some preparations for 1.0 in this issue (https://github.com/ipaddress-gem/ipaddress/issues/132).

I've updated the readme to markdown, added a PR. Will tackle a few more things soon.
