### ISSUE TITLE
gem update fails: uninitialized constant Gem::Deprecate

### ISSUE THREAD

**Issue by jim-hanlon** [ipaddress-gem/ipaddress#17]
I'm not a ruby programmer ... I pull your gem into a chef recipe. After updating to gem 1.8.11, I see

uninitialized constant Gem::Deprecate

I suspect that you need something like this:  https://github.com/jbarnette/isolate/pull/39/files

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? If it isn't, maybe we can close this issue?

By closing some old issues we reduce the list of open issues to a more manageable set.
