### ISSUE TITLE
Is this gem still under active development?

### ISSUE THREAD

**Issue by murdoch** [ipaddress-gem/ipaddress#47]
The last commit was almost 9 months ago, and there are 26 open issues, many of which have no response, and some of which provide pull-requests that have not been incorporated. 

Is there an alternative gem for handling IP addresses or does IPAddr make this one redundant?

**Comment by mrueg** [comment]
@bluemonk Is there any updated release data for version 1.0?

**Comment by bluemonk** [comment]
Hi Manuel,

This is the to-do list before releasing 1.0, in order of importance (the
way I see it):

1) Fix #40 (and the broken summarization code)
2) Fix #49
3) Add support for hashes, ranges and sets
4) Migrate tests to rspec or at least minitest

The other PR's have been either patched or are in the process to. Mike is
helping me now and he's digging into those, so we'll probably release 0.9
before 1.0.

Thanks,
Marco
