### ISSUE TITLE
Comparing an IPv4-address with IPv6-address failed

### ISSUE THREAD

**Issue by ghost** [ipaddress-gem/ipaddress#56]
Hi there,
I'm tried the gem and the latest version of IPAddress from the git repository. In both cases I got an error when comparing an IPv4-address with an IPv6-address. Can you help me with suggestions to work around the problem?

```
[1] pry(#<ApplProxyMgt::ForwardingEntry>)> IPAddress.parse('127.0.0.1').include? IPAddress.parse('::1')
NoMethodError: undefined method `to_u32' for #<IPAddress::IPv6:0x00000005e46a38>
from /home/user/.gem/ruby/2.2.0/bundler/gems/ipaddress-ce5b52474875/lib/ipaddress/ipv4.rb:537:in `include?'
```

**Comment by msimkins** [comment]
IPV4 Addresses and IPV6 Addresses are not compatible, so that comparison should not work

**Comment by dg-ratiodata** [comment]
Ok. Maybe it would be better to add a test for that and raise a proper exception?

**Comment by dg-ratiodata** [comment]
What about mapped IP4-addresses?

**Comment by alxnet** [comment]
+1 to fix, imho it would be more intuitive to return false instead of an exception:

    (IPAddress 'fd80::/64').include?(IPAddress '10.0.0.1/24')
    => false
    (IPAddress '10.0.0.1/24').include?(IPAddress 'fd80::/64')
    => NoMethodError: undefined method `to_u32' for ..

P.S.: ipaddress (0.8.0)

**Comment by ag-TJNII** [comment]
https://github.com/ipaddress-gem/ipaddress/discussions/167
