### ISSUE TITLE
When the new gem version will be issued?

### ISSUE THREAD

**Issue by vizvamitra** [ipaddress-gem/ipaddress#97]
Some changes have been made to a gem since v0.8.3. One of them is fixing the issue with IPv4#<=> (#76) which is important for what I'm currently doing (I'm forced to put a hack in my code to avoid it). So when do you plan to issue a new gem version?

**Comment by msimkins** [comment]
While I am not a maintainer of this gem, you can always either build the gem from the version held here, or you can checkout and build the gem locally. 

I have built a number of gems this way or used a (local) fork of it so that it does not change

**Comment by as3richa** [comment]
+1. 0.83 is closing in on 2 years old 😄

**Comment by dstull** [comment]
agreed - looking for a maintainer to publish new reve...instead of forking and making own

**Comment by jsmartt** [comment]
+1

**Comment by Adam21e** [comment]
@jsmartt I have forked to a new version if you are interested: https://github.com/ipaddress2-gem/ipaddress_2

**Comment by sandstrom** [comment]
Tracking this here: https://github.com/ipaddress-gem/ipaddress/issues/132

Closing this issue, as I'm going through and cleaning up some outstanding issues.
